"""empty message

Revision ID: fa3438c98b11
Revises: f723e2d7cb81
Create Date: 2023-01-30 16:24:57.139757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3438c98b11'
down_revision = 'f723e2d7cb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
